name: cascade

cas_mvsnet_ckpt_path: pretrained/casmvsnet_model_000015.ckpt
cas_mvsnet_use_backbone: false
cas_mvsnet_load_to_backbone: false
cas_mvsnet_ndepth: [48, 32, 8]
positional_encoding_num_frequencies: 2
multi_costvolume_transformer_layers: 2
multi_costvolume_transformer_num_head: 4
voxel_size_list: [32, 128, 512]
min_opacity_list: [0.1, 0.1, 0.1]