name: cascade

cas_mvsnet_ckpt_path: pretrained/casmvsnet_smooth_000015.ckpt
cas_mvsnet_use_backbone: true
cas_mvsnet_load_to_backbone: false
cas_mvsnet_ndepth: [128, 32, 8]
cas_mvsnet_cr_base_channels: [32, 16, 8]
cas_mvsnet_base_channel: 32
cas_mvsnet_geo_max_dist: 0.01
cas_mvsnet_geo_max_depth_diff: 0.01
cas_mvsnet_use_out_features: true
use_vggt: true
positional_encoding_num_frequencies: 2
feature_channels: 32
transformer_layers: 1
transformer_num_head: 2
no_ffn: False
ffn_dim_expansion: 4
max_voxels_foreach_processing: 1000000
voxel_size_list: [16, 32, 64, 128, 256, 512]
voxel_size_begin_steps: [0, 1000, 2000, 3000, 4000, 5000, 300001]
patch_size_list: [36, 25, 16, 9, 4, 1]
predict_sh_degree: 2


# params for multi-view depth predictor
downscale_factor: 4
num_depth_candidates: 32
costvolume_unet_feat_dim: 64
costvolume_unet_channel_mult: [1,1,1]
costvolume_unet_attn_res: []
gaussians_per_pixel: 1
depth_unet_feat_dim: 64
depth_unet_attn_res: []
depth_unet_channel_mult: [1, 1, 1]
multiview_trans_attn_split: 4