name: mvsnerf

num_target_views_train: 1
num_context_views_train: 3
num_target_views_test: 4
num_context_views_test: 3

dtu_train_path: config/dataset/view_sampler/mvsnerf_stored/dtu_train.lst
dtu_test_path: config/dataset/view_sampler/mvsnerf_stored/dtu_test.lst
dtu_pairs_path: config/dataset/view_sampler/mvsnerf_stored/dtu_pairs.txt
test_pairs_path: config/dataset/view_sampler/mvsnerf_stored/pairs.th